server:
  port: 8803
spring:
  application:
    name: cloud-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
turbine:
  app-config: cloud-user-center
  cluster-name-expression: "'default'"